# Generated by Django 5.0.6 on 2024-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemrenluyen',
            name='xep_loai',
            field=models.IntegerField(choices=[(1, 'Xuất Sắc'), (2, 'Giỏi'), (3, 'Khá'), (4, 'Trung Bình'), (5, 'Yếu'), (6, 'Kém')], editable=False),
        ),
        migrations.AlterField(
            model_name='thamgia',
            name='ngay_diem_danh',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
