# Generated by Django 5.0.6 on 2024-06-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0002_alter_diemrenluyen_xep_loai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieu',
            name='diem_toi_da',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thamgia',
            name='trang_thai',
            field=models.IntegerField(choices=[(0, 'Đăng Ký'), (1, 'Điểm Danh'), (2, 'Báo Thiếu'), (3, 'Không Hợp Lý')], null=True),
        ),
    ]
