# Generated by Django 5.0.6 on 2024-06-11 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0003_dieu_diem_toi_da_alter_thamgia_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoatdongngoaikhoa',
            name='tro_ly',
            field=models.ForeignKey(default=6, limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
