# Generated by Django 5.0.6 on 2024-06-12 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0004_hoatdongngoaikhoa_tro_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
