# Generated by Django 5.0.6 on 2024-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0005_sinhvien_active_sinhvien_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='tags',
        ),
    ]
