# Generated by Django 5.0.6 on 2024-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0006_remove_baiviet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='baiviets', to='trainingpoint.tag'),
        ),
    ]
