# Generated by Django 5.0.6 on 2024-06-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0007_baiviet_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
