# Generated by Django 5.0.6 on 2024-06-17 09:24

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingpoint', '0008_remove_baiviet_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocky_namhoc',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hocky_namhoc',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hocky_namhoc',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='minhchung',
            name='phan_hoi',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tro_ly',
            field=models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hoatdongngoaikhoa',
            name='dieu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainingpoint.dieu'),
        ),
        migrations.AlterField(
            model_name='hoatdongngoaikhoa',
            name='hk_nh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainingpoint.hocky_namhoc'),
        ),
        migrations.AlterField(
            model_name='hoatdongngoaikhoa',
            name='tro_ly',
            field=models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lop',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lop', to='trainingpoint.khoa'),
        ),
        migrations.AlterField(
            model_name='trolysinhvien_khoa',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingpoint.khoa'),
        ),
    ]
